name: Bug Report
description: File a bug report
title: "[Bug]: "
#assignees:
#  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior, code snippet or screenshots. If possible, attach a minimized demo project would help a lot!
      value: "Go to \'...\'\nClick on \'....\'\nScroll down to \'....\'\nSee error"
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What expected
      description: A clear and concise description of what you expected to happen.
      value: "It supposed to login success"
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of sdk you using?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
