name: New Feature
description: File a new feature request
title: "[Feature]: "
#assignees:
#  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-you-want
    attributes:
      label: Describe the feature request
      description: A clear and concise description of what you expecting to have in new Moxo SDK.
    validations:
      required: true
  - type: textarea
    id: why-you-want
    attributes:
      label: Describe the pain point
      description: Describe what's your user case or why you want this new feature.
    validations:
      required: false
